---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhiwen.
--- DateTime: 2021/9/22 10:31
---
module('BN.Cutscene', package.seeall)

DirectorSceneGradientPlayableCreator = class('DirectorSceneGradientPlayableCreator', Polaris.Cutscene.SingleClipCreator)

function DirectorSceneGradientPlayableCreator:GetClipClassStr()
    return "BN.Cutscene.DirectorSceneGradientInClip"
end
