---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lizhiwen.
--- DateTime: 2021/9/17 11:37
---
module('BN.Cutscene', package.seeall)

SceneInComponent = class('SceneInComponent')

function SceneInComponent:ctor()
    local root
    if Application.isEditor then
        root = GameObject.Find("CLICKFEEDBACK")
    else
        root = UIManager:GetRoot("CLICKFEEDBACK")
    end
    self.sceneBgGO = GameObject.New('sceneBg',typeof(UnityEngine.UI.Image))
    self.sceneBgGO:SetParent(root)
    self.sceneBgGO.transform:SetAsLastSibling()
    local rectTransform = self.sceneBgGO:GetOrAddComponent(typeof(UnityEngine.RectTransform))
    self.sceneBgGO.transform:SetLocalPos(0,0,0)
    rectTransform.anchoredPosition = Vector2(0,0)
    rectTransform.localScale = Vector3(1, 1, 1)
    rectTransform.anchorMin = Vector2.zero
    rectTransform.anchorMax = Vector2.one
    rectTransform.sizeDelta = Vector2(1656,960)

    self.sceneBgImg  = self.sceneBgGO:GetOrAddComponent(typeof(UnityEngine.UI.Image))
    self.sceneBgImg.color = Color.New(0,0,0,0)
    self.sceneBgGO:SetActive(false)
    self.sceneBgImg.raycastTarget = false
end 

function SceneInComponent:ChangeBgColor(color)
    if not goutil.IsNil(self.sceneBgGO) then
        self.sceneBgGO:SetActive(true)
        self.sceneBgImg.color = color
    end
end 

function SceneInComponent:OnDestroy()
    if not goutil.IsNil(self.sceneBgGO) then
        if CutsceneUtil.CheckIsInEditorNotRunTime() then
            GameObject.DestroyImmediate(self.sceneBgGO)
        else
            GameObject.Destroy(self.sceneBgGO)
        end
        self.sceneBgGO = nil
    end
end 