---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/8/18 19:55
---
module("BN.Cutscene",package.seeall)

local CutsceneResMgr = Polaris.Cutscene.CutsceneResMgr


---@desc 获取角色对象
---@param actorKey number
---@return GameObject
function CutsceneResMgr.GetActorGOByKey(actorKey)
    return ResMgr.GetActorGOByKey(actorKey)
end

---@desc 获取扩展预制
---@param bundleName string
---@param assetName string
---@param assetTypeEnumInt ExportAssetType
---@return PrefabAsset
function CutsceneResMgr.GetExtPrefab(bundleName,assetName,assetTypeEnumInt)
    return ResMgr.GetExtPrefab(bundleName,assetName,assetTypeEnumInt)
end

---@desc 获取档期已加载的timeline序列化资源
---@return UnityEngine.Timeline.TimelineAsset
function CutsceneResMgr.GetCurTimelineAsset()
    return ResMgr.GetCurTimelineAsset()
end 