---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/8/18 17:50
---
local TimelinePlayableHandlerMgr = Polaris.Cutscene.CutsceneTimelinePlayableHandlerMgr


local CutsceneTrackType = Polaris.Cutscene.CutsceneTrackType
local LocalCutsceneTrackType = BN.Cutscene.CutsceneTrackType
local RuntimeEditorCutsceneTrackType = BN.Cutscene.CSharpRuntimeEditorCutsceneTrackType

TimelinePlayableHandlerMgr.playableCreatorClassMap = {
    [CutsceneTrackType.ActorInfoTrackType] = "BN.Cutscene.ActorInfoPlayableCreator",
    [CutsceneTrackType.ActorControlTrackType] = "BN.Cutscene.ActorControlPlayableCreator",
    [CutsceneTrackType.ActorTransformTrackType] = "BN.Cutscene.ActorTransformPlayableCreator",
    [CutsceneTrackType.EventTriggerTrackType] = "BN.Cutscene.EventTriggerPlayableCreator",
    [CutsceneTrackType.CameraInfoTrackType] = "BN.Cutscene.CameraInfoPlayableCreator",
    [LocalCutsceneTrackType.DirectorOverlayUITrackType] = "BN.Cutscene.DirectorOverlayUIPlayableCreator",
    [LocalCutsceneTrackType.DirectorSceneGradientTrackType] = "BN.Cutscene.DirectorSceneGradientPlayableCreator",
    [LocalCutsceneTrackType.DirectorSceneAudioTrackType] = "BN.Timeline.AkSoundPlayableCreator",
    [LocalCutsceneTrackType.DirectorSceneBGMTrackType] = "BN.Cutscene.CutsAKSoundBGMPlayableCreator",
    [LocalCutsceneTrackType.DirectorVideoTrackType] = "BN.Cutscene.VideoPlayableCreator",
    [LocalCutsceneTrackType.DirectorDollyCameraTrackType] = "BN.Cutscene.DollyCameraPlayableCreator",
    [LocalCutsceneTrackType.DirectorBlurTrackType] = "BN.Cutscene.CutsceneBlurPlayableCreator",
    [LocalCutsceneTrackType.ActorAudioTrackType] = "BN.Cutscene.ActorAudioPlayableCreator",
    [LocalCutsceneTrackType.DirectorEffectTrackType] = "BN.Cutscene.DirectorEffectPlayableCreator",
    [LocalCutsceneTrackType.DirectorImpulseTrackType] = "BN.Cutscene.DirectorImpulsePlayableCreator",
    [LocalCutsceneTrackType.DirectorTimeScaleTrackType] = "BN.Cutscene.DirectorTimeScalePlayableCreator",
    [LocalCutsceneTrackType.DirectorInteractTrackType] = "BN.Cutscene.DirectorInteractPlayableCreator",
    [LocalCutsceneTrackType.DirectorCGSpriteTrackType] = "BN.Cutscene.DirectorCGSpritePlayableCreator",
    [LocalCutsceneTrackType.DirectorMemoriesTrackType] = "BN.Cutscene.DirectorMemoriesPlayableCreator",
    [LocalCutsceneTrackType.DirectorSpeedLineTrackType] = "BN.Cutscene.DirectorSpeedLinePlayableCreator",
    [LocalCutsceneTrackType.DirectorLightControlTrackType] = "BN.Cutscene.DirectorLightControlPlayableCreator",
    [LocalCutsceneTrackType.DirectorBlinkTrackType] = "BN.Cutscene.DirectorBlinkPlayableCreator",
    [LocalCutsceneTrackType.DirectorTotalTransformTrackType] = "BN.Cutscene.TotalTransformPlayableCreator",
    [LocalCutsceneTrackType.SceneEffInstantiateTrackType] = "BN.Cutscene.SceneEffInstantiatePlayableCreator",
    [LocalCutsceneTrackType.HideEnvironmentTrackType] = "BN.Cutscene.HideEnvironmentPlayableCreator",
    [LocalCutsceneTrackType.HideCinemachineClipVirCamTrackType] = "BN.Cutscene.HideCinemachineClipVirCamPlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorRadialBlurTrackType] = "BN.Cutscene.RadialBlurKFramePlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorPosterizeTrackType] = "BN.Cutscene.PosterizeKFramePlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorDarkSceneTrackType] = "BN.Cutscene.DirectorDarkScenePlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorMotionBlurKFrameTrackType] = "BN.Cutscene.MotionBlurKFramePlayableCreator",
    [LocalCutsceneTrackType.ModifyObjLayerTrackType] = "BN.Cutscene.ModifyObjLayerPlayableCreator",
    [LocalCutsceneTrackType.ChangeRolePartMaterialTrackType] = "BN.Cutscene.CutsChangeMaterialPlayableCreator",
    [LocalCutsceneTrackType.ActorFollowTrackType] = "BN.Cutscene.ActorFollowPlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorWeatherTrackType] = "BN.Cutscene.DirectorWeatherPlayableCreator",
    [LocalCutsceneTrackType.GhostTrackType] = "BN.Cutscene.GhostPlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorPostProcessBloomTrackType] = "BN.Cutscene.DirectorPostProcessBloomPlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorPostProcessVignetteTrackType] = "BN.Cutscene.DirectorPostProcessVignettePlayableCreator",
    [RuntimeEditorCutsceneTrackType.DirectorPostProcessTonemappingTrackType] = "BN.Cutscene.DirectorPostProcessTonemappingPlayableCreator",
}