---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/8/19 17:09
---

module('Polaris.Cutscene', package.seeall)

MultiClipCreator = class('MultiClipCreator',TimelinePlayableCreateBase)

function MultiClipCreator:CreatePlayableBehaviour(playable,params)
    local paramsTable = cjson.decode(params)
    local clipType = tonumber(paramsTable["clipType"])
    local playableClip = self:GetPlayableClip(clipType)
    local clip = playableClip.New()
    clip:Handle(playable,paramsTable)
    return clip
end

function MultiClipCreator:GetPlayableClip(clipType)
    if not self.clipTypeToClassStr then
        self.clipTypeToClassStr = self:GetClipClassTable()
    end 
    local classStr = self.clipTypeToClassStr[clipType]
    return CutsceneUtil.GetClassByStr(classStr)
end

function MultiClipCreator:GetClipClassTable()
    return {}
end