---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/8/19 17:56
---

module('Polaris.Cutscene', package.seeall)

SingleClipCreator = class('SingleClipCreator',TimelinePlayableCreatorBase)

function SingleClipCreator:CreatePlayableBehaviour(playable,params)
    local paramsTable
    if params and params ~= "" and params ~= cjson.null then
        paramsTable = cjson.decode(params)
    end
    local clipClass = CutsceneUtil.GetClassByStr(self:GetClipClassStr())
    local clip = clipClass.New()
    clip:Handle(playable,paramsTable)
    return clip
end

function SingleClipCreator:GetClipClassStr()
    return ""
end
