---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/2/26 11:38
---
module('Polaris.Cutscene', package.seeall)

TimelineClipBase = class('TimelineClipBase')

function TimelineClipBase:Handle(playable,...)
    self.playable = playable
    self:OnBehaviourPlay(...)
end

function TimelineClipBase:OnBehaviourPlay(...)

end

-- //当时间轴在该代码区域：Pause、Stop时
-- //当从头播放该TimeLine时执行一次
-- //当时间轴驶出该代码区域时执行一次
function TimelineClipBase:OnBehaviourPause(playable)

end

-- //当时间轴整个TimeLine：Stop 时
-- //该TimeLine播放结束时
function TimelineClipBase:OnPlayableDestroy(playable)

end

-- //当时间轴在该代码片段时，每帧执行(ProcessFrame之前)
function TimelineClipBase:PrepareFrame(playable)

end

--//当时间轴在该代码片段时，每帧执行(在PrepareFrame之后)
function TimelineClipBase:ProcessFrame(playable)

end

--//生命周期LateUpdate执行
function TimelineClipBase:LateUpdate(playable)

end