---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lihangyu.
--- DateTime: 2021/8/18 19:52
---
module('Polaris.Cutscene', package.seeall)

CutsceneResMgr = SingletonClass('CutsceneResMgr')
local instance = CutsceneResMgr

function CutsceneResMgr.GetActorGOByKey(actorKey) 
    
end

function CutsceneResMgr.GetExtPrefab(bundleName,assetName,assetTypeEnumInt)
    
end

function CutsceneResMgr.GetCurTimelineAsset()
    
end 